name: David Edwards
timezone: America/Chicago
encoding: utf-8
permalink: /blog/:year/:month/:day/:title
exclude: [/CNAME, /README.md, /package.json, /package-lock.json, /node_modules]
sass:
  load_paths:
    - node_modules
plugins:
  - jekyll-sitemap
